feat: Add new cloud account type GCP Sidekick Integration
lacework/go-sdk pull request #1028
Opened 2022-11-21 07:19 UTC by ammarekbote

This features adds the Sidekick Integration type needed by terraform provider module to access the new integration.

Closes Internal Ticker - #RAIN-43475

## How did you test this change?
Created and deleted integration from provider repo. 
    Added unit test to verify create, get and update operations for GcpSidekick integration.

```
    bash-3.2$ go test -v -run "TestCloudAccountsGcpSidekick"
    === RUN   TestCloudAccountsGcpSidekickCreate
    --- PASS: TestCloudAccountsGcpSidekickCreate (0.00s)
    === RUN   TestCloudAccountsGcpSidekickGet
    --- PASS: TestCloudAccountsGcpSidekickGet (0.00s)
    === RUN   TestCloudAccountsGcpSidekickUpdate
    --- PASS: TestCloudAccountsGcpSidekickUpdate (0.00s)
    PASS
    ok      github.com/lacework/go-sdk/api  0.149s
    bash-3.2$
```

## Issue

RAIN-43475

2022-11-21 17:03 UTC, alannix-lw requested changes
Looks good in terms of implementation, but let's either make sure we get tests implemented similar to what we have for the AWS AWLS integrations, or create an action item to do them shortly.

2022-11-21 17:03 UTC, alannix-lw commented on api/cloud_accounts_gcp_sidekick.go
> +}
```suggestion
type GcpSidekickData struct {
	Credentials GcpSidekickCredentials `json:"credentials"`
	IDType      string                 `json:"idType"`
	// Either the org id or project id
	ID                string `json:"id"`
	ScanningProjectId string `json:"scanningProjectId"`
	SharedBucket      string `json:"sharedBucketName"`
	FilterList        string `json:"filterList,omitempty"`
	QueryText         string `json:"queryText,omitempty"`
	//ScanFrequency in hours, 24 == 24 hours
	ScanFrequency           int  `json:"scanFrequency"`
	ScanContainers          bool `json:"scanContainers"`
	ScanHostVulnerabilities bool `json:"scanHostVulnerabilities"`
}
```

2022-11-21 17:20 UTC, ammarekbote commented
> Looks good in terms of implementation, but let's either make sure we get tests implemented similar to what we have for the AWS AWLS integrations, or create an action item to do them shortly.

Agreed. I missed this while adding the terraform provider tests. Will add a test for this shortly.

2022-11-22 15:49 UTC, alannix-lw approved these changes
LGTM 👍

2022-11-22 17:55 UTC, dmurray-lacework approved these changes
<img src="https://media3.giphy.com/media/pCO5tKdP22RC8/giphy.gif"/>

2022-11-22 21:39 UTC, merged