refactor: do not filter csv output for vuln ctr show
lacework/go-sdk pull request #1220
Opened 2023-04-05 18:26 UTC by dmurray-lacework

## Summary

## How did you test this change?

## Issue

2023-04-11 13:19 UTC, jon-stewart approved these changes

2023-04-19 06:45 UTC, afiune requested changes
tested it and when passing a non-existing CVE it returns this:
```
$ lacework vulnerability ctr show sha256:4f299b4fc8f7b7daf411401140a0b15c1b29f5ddb547d21f4005093c566c8a98 --details  CVE-1234
Great news! This container image has no vulnerabilities... (time for 🍕 )
```

2023-04-19 14:33 UTC, dmurray-lacework commented
> tested it and when passing a non-existing CVE it returns this:
> 
> ```
> $ lacework vulnerability ctr show sha256:4f299b4fc8f7b7daf411401140a0b15c1b29f5ddb547d21f4005093c566c8a98 --details  CVE-1234
> Great news! This container image has no vulnerabilities... (time for 🍕 )
> ```

@afiune the change to accept a single CVE hasn't been merged yet.

2023-04-19 15:07 UTC, afiune commented
@dmurray-lacework Apologies, I was reviewing two of your PRs late at night and I put the comment in the wrong one, this comment is meant for https://github.com/lacework/go-sdk/pull/1232 which I noticed you already fixed the problem.

2023-04-20 15:36 UTC, afiune approved these changes
<img src="https://media1.giphy.com/media/m8jPxnABaL6dhnceRP/giphy-downsized-medium.gif"/>

2023-04-20 15:50 UTC, merged