feat(cli): New CVE-ID parameter to 'lacework vuln ctr show cmd'
lacework/go-sdk pull request #1232
Opened 2023-04-13 15:06 UTC by dmurray-lacework

## Summary

Add new optional parameter to  'lacework vuln ctr show cmd' 
Usage:

```
❯ lacework vuln ctr show lacework vuln ctr show <sha> CVE-1234-56789             
                 CVE DETAILS                  
----------------------------------------------
    CVE ID            CVE-2021-24215          
    SEVERITY          Medium                  
    PACKAGE           example                 
    NAMESPACE         alpine:test             
    FEED              lacework                
    SRC                                       
    START TIME        2022-11-14T00:20:57Z    
    VERSION FORMAT    apk                     
    CURRENT VERSION   1.00.0-r1               
    FIX VERSION       1.20.00-r0              
    STATUS            VULNERABLE              
                                       
                          INTRODUCED IN LAYERS                          
------------------------------------------------------------------------
  COPY                                                                  
  dir:abcdefghjljk1234abcdef  
  in ./node_modules 
------------------------------------------------------------------------                                                    
  COPY                                                                  
  dir:abcdefghjljk1234abcdef  
  in ./node_modules 
------------------------------------------------------------------------                                                    
  COPY                                                                  
  dir:abcdefghjljk1234abcdef  
  in ./node_modules
------------------------------------------------------------------------                                                     
  COPY                                                                  
  dir:abcdefghjljk1234abcdef  
  in ./node_modules                                                     

```

## How did you test this change?

Tests
- [x] `TestBuildVulnContainerAssessmentReportsWithSingleCveFilter`
- [x] `TestBuildVulnContainerAssessmentReportsWithSingleCveFilterPackages`
- [x] `TestBuildVulnContainerAssessmentReportsWithSingleCveFilterJson`
- [x] `TestV2VulnerabilitiesFilterSingleVulnID`

Manual
`lacework vuln ctr show <sha> [cve_id]`
`lacework vuln ctr show <sha> [cve_id] --json`
`lacework vuln ctr show <sha> [cve_id] --packages`

## Issue

https://lacework.atlassian.net/browse/GROW-1440

2023-04-19 15:31 UTC, afiune requested changes

2023-04-19 15:31 UTC, afiune commented
This is also a `fix:` not a `chore:`

2023-04-19 19:51 UTC, afiune commented on api/v2_vulnerabilities_test.go
> +	json.Unmarshal([]byte(mockVulnerabilitiesContainersResponse()), &response)
What if there are more than one vulnerability information about the same CVE id?

2023-04-19 19:54 UTC, afiune commented on api/v2_vulnerabilities_test.go
> +	json.Unmarshal([]byte(mockVulnerabilitiesContainersResponse()), &response)
I tried out "dirty image" that has this CVE ID four times and it doesn't really display the information correctly:
```
lacework vulnerability ctr show sha256:77b2d2246518044ef95e3dbd029e51dd477788e5bf8e278e418685aabc3fe28a CVE-2022-1271
```

2023-04-20 10:30 UTC, dmurray-lacework commented on api/v2_vulnerabilities_test.go
> +	json.Unmarshal([]byte(mockVulnerabilitiesContainersResponse()), &response)
I've updated this to repeat the table when the are multiple results of the same cve-id.

2023-05-16 17:06 UTC, afiune reviewed
I will come back and review this.

2023-05-25 22:11 UTC, afiune approved these changes
Let's just roll with it... 

<img src="https://media0.giphy.com/media/9GIFzN0j8j8f3FoCu2/giphy.gif"/>

2023-05-25 22:19 UTC, merged