feat(cli): lacework policy command
lacework/go-sdk pull request #422
Opened 2021-05-21 21:52 UTC by hazedav

Building out lacework policy command functionality.

Includes:
- `lacework policy list`
- `lacework policy show`
- `lacework policy create`
- `lacework policy update`
- `lacework policy delete`

ALLY-422

2021-05-21 21:52 UTC, hazedav commented
This is final review of work that had individual reviews per each of the subtasks under ALLY-422.  Thanks!

2021-05-25 20:14 UTC, afiune requested changes
only one single blocker, the rest looks great!

2021-05-25 20:14 UTC, afiune commented on api/api.go
> +	apiPolicy = "external/lqlPolicies"
```suggestion
	apiPolicy = "v1/external/lqlPolicies"
```

2021-05-25 20:40 UTC, hazedav commented on api/api.go
> +	apiPolicy = "external/lqlPolicies"
Fixed.

2021-05-25 21:06 UTC, afiune approved these changes
![tenor-46500580](https://user-images.githubusercontent.com/5712253/119568362-a9547680-bd6a-11eb-8e55-544dc4653920.gif)

2021-05-25 21:50 UTC, merged