feat(cli): alert profiles command
lacework/go-sdk pull request #792
Opened 2022-05-19 14:38 UTC by dmurray-lacework

Signed-off-by: Darren Murray <darren.murray@lacework.net>

## Summary

## How did you test this change?

## Issue

2022-05-23 14:54 UTC, afiune commented on cli/cmd/alert_profiles.go
> +		Long: `Manage alert profiles to define how your LQL queries get consumed into alerts
```suggestion
		Long: `Manage alert profiles to define how your LQL queries get consumed into alerts.
```

2022-05-23 14:54 UTC, afiune commented on cli/cmd/alert_profiles.go
> +the new profile extends and a list of alert templates`,
```suggestion
the new profile extends and a list of alert templates.`,
```

2022-05-23 15:03 UTC, afiune commented on cli/cmd/alert_profiles.go
> +				rows = append(rows, []string{profile.Guid, profile.Extends})
can we order this list

2022-05-23 15:23 UTC, afiune commented on cli/cmd/alert_profiles_test.go
> +`
What about this output instead?
```
        ALERT PROFILE ID                 EXTENDS
---------------------------------+---------------------
  LW_HE_MACHINES_DEFAULT_PROFILE   LW_LPP_BaseProfile

                                                          ALERT TEMPLATES
-----------------------------------------------------------------------------------------------------------------------------------
              NAME                       EVENT NAME                      DESCRIPTION                        SUBJECT
  ---------------------------+--------------------------------+--------------------------------+---------------------------------
    HE_Machine_NewViolation    LW Host Entity Machine           {{_OCCURRENCE}} Violation for    {{_OCCURRENCE}} violation
                               Violation Alert                  machine {{HOSTNAME}}             detected for machine
                                                                                                 {{HOSTNAME}}
    HE_Machine_PolicyChanged   LW Host Entity Machine           {{_OCCURRENCE}} Violation for    {{_OCCURRENCE}} violation
                               Violation Alert                  machine {{HOSTNAME}}             detected for machine
                                                                                                 {{HOSTNAME}}
    HE_Machine_Violation       LW Host Entity Machine           {{_OCCURRENCE}} Violation for    {{_OCCURRENCE}} violation
                               Violation Alert                  machine {{HOSTNAME}}             detected for machine
                                                                                                 {{HOSTNAME}}

                                                                       FIELDS
--------------------------------------------------------------------------------------------------------------------------------------
  OS, MID, RECORD_CREATED_TIME ,_EVENT_COUNT ,_POLICY_ID ,_SEVERITY ,KERNEL_ARGS ,HOSTNAME ,DEFAULT_ROUTER ,OS_VERSION ,
  LAST_BOOT_TIME ,KERNEL_VERSION ,KERNEL_RELEASE ,TAGS ,_PRIMARY_TAG ,ROUTE ,OS_DESC ,DOMAIN ,_POLICY_DESCRIPTION ,LAST_BOOT_REASON ,
  MEMORY_INFO ,_RISK ,_OCCURRENCE ,CPU_INFO ,KERNEL ,_POLICY_TITLE ,MACHINE_ID ,_POLICY_SEVERITY

To use fields inside the description or subject of a template enclose the name between double brakets. For example: '{{FIELD_NAME}}'
```

2022-05-23 15:24 UTC, afiune commented on cli/cmd/alert_profiles.go
> +			cli.OutputHuman(fmt.Sprintf("The alert profile was created with GUID %s \n", response.Data.Guid))
We display GUID here but in the SHOW table we display ID. Can we match them?

2022-05-23 15:25 UTC, afiune commented on cli/cmd/alert_profiles.go
> +func getAlertProfiles() []string {
can we unit test this function?

2022-05-23 15:25 UTC, afiune commented on cli/cmd/alert_profiles.go
> +	}
can we order this list?

2022-05-23 15:26 UTC, afiune commented on cli/cmd/alert_profiles.go
> +	// delete command is used to remove a lacework alert profile by resource id
```suggestion
	// delete command is used to remove a lacework alert profile by id
```

2022-05-23 15:27 UTC, afiune commented on cli/cmd/alert_profiles.go
> +			return nil
Are these IDs or GUIDs?

2022-05-23 15:28 UTC, afiune commented on cli/cmd/alert_profiles.go
> +			cli.OutputHuman(fmt.Sprintf("The alert profile with GUID %s was deleted \n", args[0]))
```suggestion
			cli.OutputHuman("The alert profile with GUID %s was deleted \n", args[0])
```

2022-05-24 08:40 UTC, benradstone commented on integration/test_resources/help/alert-profile
> +the new profile extends and a list of alert templates
```suggestion
the new profile extends and a list of alert templates.
```

2022-05-24 08:40 UTC, benradstone commented on integration/test_resources/help/alert-profile
> +Manage alert profiles to define how your LQL queries get consumed into alerts
```suggestion
Manage alert profiles to define how your LQL queries get consumed into alerts.
```

2022-05-24 08:41 UTC, benradstone commented on integration/test_resources/help/alert-profile_delete
> +Delete a single alert profile by it's ID.
```suggestion
Delete a single alert profile by its ID.
```

2022-05-24 08:41 UTC, benradstone commented on integration/test_resources/help/alert-profile_show
> +Show a single alert profile by it's ID.
```suggestion
Show a single alert profile by its ID.
```

2022-05-24 08:42 UTC, benradstone requested changes
Some spelling and grammatical comments, feel free to commit them.

2022-05-24 09:37 UTC, dmurray-lacework commented on cli/cmd/alert_profiles.go
> +			return nil
IDs

2022-05-25 09:43 UTC, benradstone approved these changes

2022-05-26 13:06 UTC, merged