refactor: use v2/AgentInfo for agents list command
lacework/go-sdk pull request #866
Opened 2022-07-18 12:51 UTC by dmurray-lacework

Signed-off-by: Darren Murray <darren.murray@lacework.net>

## Summary

Use `v2/AgentInfo` api instead of `Entities/MachineDetails` in agent list command. Add status field to output

## How did you test this change?

Run `lacework agent list`

## Issue

https://lacework.atlassian.net/browse/ALLY-1071

2022-07-20 23:11 UTC, afiune commented on api/agent_access_tokens.go
> +	LastUpdate   string    `json:"lastUpdate"`
We need to change this to:
```suggestion
	LastUpdate   time.Time    `json:"lastUpdate"`
```
But we need to wait for this change to be released: https://github.com/lacework/services/pull/8095

Jira: https://lacework.atlassian.net/browse/RAIN-34237

2022-07-20 23:28 UTC, afiune commented on cli/cmd/agent_list.go
> +			[]string{"MID", "Short Agent Token", "Hostname", "Name", "Status", "IP Address", "External IP", "OS Arch", "Last Checkin"},
Add column created time and use the `lastUpdate` field for the Last Checkin column.

Order table like:
```suggestion
			[]string{"MID", "Short Agent Token", "Status", "Hostname", "Name", "IP Address", "External IP", "OS Arch", "Last Check-in", "Created Time"},
```

Choose if Created at or Created time

2022-08-04 07:57 UTC, dmurray-lacework commented on cli/cmd/agent_list.go
> +			hostname = fmt.Sprintf("%s...", hostname[:20])
Are we truncating for formatting purposes? After we've obscured information how does the user see the full value, the json response?

2022-08-04 08:00 UTC, dmurray-lacework commented on cli/cmd/agent_list.go
> +			hostname = fmt.Sprintf("%s...", hostname[:20])
If we are going to include fixed field limits we should have a single function that is shared for consistency. If it's possible to include it in the tablewriter that would be nice.

2022-08-04 19:39 UTC, afiune requested changes

2022-08-04 19:39 UTC, afiune commented on api/agent_access_tokens.go
> +func (svc *AgentAccessTokensService) Search(response interface{}, filters SearchFilter) error {
Why is this new function inside the `AgentAccessTokensService`??? This is really wrong!

Every API v2 schema should be its own service 😓 - I will have to refactor this too.

2022-08-04 23:15 UTC, afiune approved these changes
![tenor-211043291](https://user-images.githubusercontent.com/5712253/182970793-4e1d0ca9-e31c-401f-9781-cc327b484923.gif)

2022-08-04 23:18 UTC, merged