refactor: migrate vuln host list-hosts to use v2
lacework/go-sdk pull request #912
Opened 2022-09-15 11:47 UTC by dmurray-lacework

Signed-off-by: Darren Murray <darren.murray@lacework.net>

## Summary

## How did you test this change?

## Issue

2022-09-28 14:47 UTC, afiune commented on internal/array/sort.go
> +func Sort2DDescending(slice [][]string) {
add test please

2022-09-28 14:49 UTC, afiune commented on cli/cmd/vuln_host.go
> +			array.Sort2DDescending(rows)
This might break the previous sorting by severity inside `hostVulnCVEsTableForHostView()`

2022-10-06 18:40 UTC, afiune requested changes

2022-10-06 20:18 UTC, afiune commented on api/v2_vulnerabilities.go
> +type VulnCveSummary struct {
This struct is massively used but it not being test it anywhere, I run some commands and it doesn't even have JSON tags so this shows as:
```
  "CVE-2022-39842": {
    "Count": 1,
    "Host": { ... },
    "Hostnames": [
      "ip-10-0-1-48"
    ]
  }
```

2022-10-07 12:22 UTC, dmurray-lacework commented on api/v2_vulnerabilities.go
> +type VulnCveSummary struct {
Could you point to where this is being used in the json output? It should not be used in a json output.

2022-10-07 13:10 UTC, dmurray-lacework commented on cli/cmd/vuln_host.go
>  			expired := cli.ReadCachedAsset(cacheKey, &assessment)
It doesn't panic but, we get 

`Great news! This host has no vulnerabilities... (time for 🌮 )
`

2022-10-07 13:11 UTC, dmurray-lacework commented on cli/cmd/vuln_host.go
>  			expired := cli.ReadCachedAsset(cacheKey, &assessment)
We could add "v2" to the cache path?

2022-10-07 13:13 UTC, dmurray-lacework commented on cli/cmd/vuln_host.go
>  			expired := cli.ReadCachedAsset(cacheKey, &assessment)
https://github.com/lacework/go-sdk/pull/912/files#diff-d728049046916afa9d13ad91ca1e3c6a2f2898d77b1b10a99000dede86d58d29R318

2022-10-07 14:44 UTC, afiune commented on cli/cmd/vuln_host.go
> +func cvesSummary(hosts []api.VulnerabilityHost) map[string]api.VulnCveSummary {
can we unit test?

2022-10-07 14:51 UTC, afiune commented on api/v2_vulnerabilities.go
> +type VulnCveSummary struct {
This is not used in the `api` package at all, move it to the `cli` since you are using it there.

2022-10-07 14:53 UTC, afiune commented on cli/cmd/vuln_host.go
> -	assessment.CVEs = filteredCves
this is a regression since we are not filtering the JSON output and before we were doing it here.

2022-10-13 15:54 UTC, afiune approved these changes
![tenor-217042670](https://user-images.githubusercontent.com/5712253/195645710-d0b00996-49bc-46c4-9387-de542a032760.gif)

2022-10-26 13:09 UTC, merged