Crioux/fix limit num scan
lacework/go-sdk pull request #978
Opened 2022-10-21 19:35 UTC by crioux

## Summary

Was experiencing an inability to create inline container registries from the cli. The schema required LimitNumScan to be a string, and it was a number. 

`lacework container-registry create` was unable to create an 'inline scanner' container registry.

It was effectively doing this: 

```
lacework api post /api/v2/ContainerRegistries -d "{\"name\":\"foo\",\"type\":\"ContVulnCfg\",\"enabled\":1,\"data\":{\"registryType\":\"INLINE_SCANNER\",\"limitNumScan\":30}}"

ERROR unable to send the request:
  [POST] https://customerdemo.lacework.net/api/v2/ContainerRegistries
  [400] Error validating integration. Please verify the configuration details entered.
```

Where the 'limitNumScan' should have been the string "30" not the number 30.

## How did you test this change?

Verified the change allowed `lacework container-registry create` to operate correctly.

![image](https://user-images.githubusercontent.com/819652/197275136-cf9e076f-4dcd-4f97-ad28-fd3dc4b91d42.png)

## Issue

https://lacework.atlassian.net/browse/RAIN-38906
also should be able to close
https://lacework.atlassian.net/browse/RAIN-33574
now as well, as it is derived from the same underlying issue

2022-10-25 14:30 UTC, dmurray-lacework requested changes
Hey @crioux, thank you for creating this PR. Can you move the go.1.16 deprecations and linting changes to a new PR. There is a lot of noise in this PR with 96 files changed.

2022-10-28 14:22 UTC, crioux commented
@dmurray-lacework I removed the refactoring/cleanup and will put that on its own PR.

2022-10-31 09:55 UTC, dmurray-lacework approved these changes

2022-10-31 12:26 UTC, dmurray-lacework commented
Approved @crioux. But merge is blocked due to unsigned commits. Can you rebase and push with a signed commit.

2022-11-01 15:55 UTC, merged